using App.Core.Enums;
using App.Core.Abstractions;

namespace App.Core.Services;

public sealed class HardcodedQueryStore : IQueryStore
{
    public string GetQuery(DatabaseProvider provider, QueryEntity entity)
    {
        return provider switch
        {
            DatabaseProvider.MSSQL => GetMssqlQuery(entity),
            DatabaseProvider.MySQL => GetMysqlQuery(entity),
            DatabaseProvider.Sqlite => GetSqliteQuery(entity),
            _ => throw new ArgumentOutOfRangeException(nameof(provider), provider, "Unsupported database provider.")
        };
    }

    private static string GetMssqlQuery(QueryEntity entity) => entity switch
    {
        QueryEntity.Playerchecker => "SELECT TOP (100) c.sid AS Player_ID, c.name AS Player_Name, c.account AS Account, c.lv AS [Level], ISNULL(sr.value, '') AS Job_Name, CASE WHEN c.login_time IS NOT NULL AND (c.logout_time IS NULL OR c.logout_time < c.login_time) THEN 'ONLINE' ELSE 'OFFLINE' END AS Online_Status FROM [{{TelecasterName}}].dbo.Character AS c LEFT JOIN [{{ArcadiaName}}].dbo.JobResource AS jr ON c.job = jr.id LEFT JOIN [{{ArcadiaName}}].dbo.{{StringResource}} AS sr ON jr.text_id = sr.code ORDER BY c.sid DESC;",
        QueryEntity.PlayercheckerByCharName => "SELECT TOP (500) c.sid AS Player_ID, c.name AS Player_Name, c.account AS Account, c.lv AS [Level], ISNULL(sr.value, '') AS Job_Name, CASE WHEN c.login_time IS NOT NULL AND (c.logout_time IS NULL OR c.logout_time < c.login_time) THEN 'ONLINE' ELSE 'OFFLINE' END AS Online_Status FROM [{{TelecasterName}}].dbo.Character AS c LEFT JOIN [{{ArcadiaName}}].dbo.JobResource AS jr ON c.job = jr.id LEFT JOIN [{{ArcadiaName}}].dbo.{{StringResource}} AS sr ON jr.text_id = sr.code WHERE c.name LIKE @SearchTerm ORDER BY c.lv DESC;",
        QueryEntity.PlayercheckerByAccount => "SELECT TOP (500) c.sid AS Player_ID, c.name AS Player_Name, c.account AS Account, c.lv AS [Level], ISNULL(sr.value, '') AS Job_Name, CASE WHEN c.login_time IS NOT NULL AND (c.logout_time IS NULL OR c.logout_time < c.login_time) THEN 'ONLINE' ELSE 'OFFLINE' END AS Online_Status FROM [{{TelecasterName}}].dbo.Character AS c LEFT JOIN [{{ArcadiaName}}].dbo.JobResource AS jr ON c.job = jr.id LEFT JOIN [{{ArcadiaName}}].dbo.{{StringResource}} AS sr ON jr.text_id = sr.code WHERE c.account LIKE @SearchTerm ORDER BY c.slot ASC;",
        QueryEntity.PlayercheckerAll => "SELECT c.sid AS Player_ID, c.name AS Player_Name, c.account AS Account, c.lv AS [Level], ISNULL(sr.value, '') AS Job_Name, CASE WHEN c.login_time IS NOT NULL AND (c.logout_time IS NULL OR c.logout_time < c.login_time) THEN 'ONLINE' ELSE 'OFFLINE' END AS Online_Status FROM [{{TelecasterName}}].dbo.Character AS c LEFT JOIN [{{ArcadiaName}}].dbo.JobResource AS jr ON c.job = jr.id LEFT JOIN [{{ArcadiaName}}].dbo.{{StringResource}} AS sr ON jr.text_id = sr.code ORDER BY c.sid DESC;",
        QueryEntity.PlayercheckerOnline => "SELECT c.sid AS Player_ID, c.name AS Player_Name, c.account AS Account, c.lv AS [Level], ISNULL(sr.value, '') AS Job_Name, 'ONLINE' AS Online_Status FROM [{{TelecasterName}}].dbo.Character AS c LEFT JOIN [{{ArcadiaName}}].dbo.JobResource AS jr ON c.job = jr.id LEFT JOIN [{{ArcadiaName}}].dbo.{{StringResource}} AS sr ON jr.text_id = sr.code WHERE c.login_time IS NOT NULL AND (c.logout_time IS NULL OR c.logout_time < c.login_time) ORDER BY c.sid DESC;",
        QueryEntity.PlayerInventory => "SELECT i.code AS Item_ID, ISNULL(sr.value, 'Unknown') AS Item_Name, i.cnt AS [Count], i.level AS [Level], i.enhance AS Enhance, i.wear_info, i.awaken_sid, i.random_option_sid, i.summon_code, ir.icon_file_name AS icon_file_name FROM [{{TelecasterName}}].dbo.Item AS i INNER JOIN [{{ArcadiaName}}].dbo.ItemResource AS ir ON i.code = ir.id INNER JOIN [{{ArcadiaName}}].dbo.{{StringResource}} AS sr ON ir.name_id = sr.code WHERE i.owner_id = @OwnerId ORDER BY i.code ASC;",
        QueryEntity.PlayerWarehouse => "SELECT i.code AS Item_ID, ISNULL(sr.value, 'Unknown') AS Item_Name, i.cnt AS [Count], i.level AS [Level], i.enhance AS Enhance, i.wear_info, i.awaken_sid, i.random_option_sid, i.summon_code, ir.icon_file_name AS icon_file_name FROM [{{TelecasterName}}].dbo.Item AS i INNER JOIN [{{ArcadiaName}}].dbo.ItemResource AS ir ON i.code = ir.id INNER JOIN [{{ArcadiaName}}].dbo.{{StringResource}} AS sr ON ir.name_id = sr.code WHERE i.account_id = (SELECT TOP 1 a.account_id FROM [{{AuthName}}].dbo.{{AccountsName}} AS a WHERE a.login_name = @AccountName) ORDER BY i.code ASC;",
        QueryEntity.Monsters => "SELECT id.[id], n.[value] AS [name], id.[level], v.[value] AS [location] FROM [{{ArcadiaName}}].dbo.{{MonsterResource}} id LEFT JOIN [{{ArcadiaName}}].dbo.{{StringResource}} n ON id.[name_id] = n.[code] LEFT JOIN [{{ArcadiaName}}].dbo.{{StringResource}} v ON id.[location_id] = v.[code] ORDER BY id.[id] ASC;",
        QueryEntity.Items => "SELECT i.id AS Item_ID, s.[value] AS Name_EN, i.[icon_file_name] AS icon_file_name FROM [{{ArcadiaName}}].dbo.{{ItemResource}} i INNER JOIN [{{ArcadiaName}}].dbo.{{StringResource}} AS s ON i.name_id = s.code ORDER BY Item_ID ASC;",
        QueryEntity.Skills => "SELECT id.[id] AS Skill_id, n.[value] AS Skillname, id.[icon_file_name] AS icon_file_name FROM [{{ArcadiaName}}].dbo.{{SkillResource}} AS id LEFT JOIN [{{ArcadiaName}}].dbo.{{StringResource}} AS n ON id.text_id = n.code ORDER BY Skill_id ASC;",
        QueryEntity.States => "SELECT sr.state_id, n.[value] AS buff_name, sr.[icon_file_name] AS icon_file_name FROM [{{ArcadiaName}}].dbo.{{StateResource}} sr LEFT JOIN [{{ArcadiaName}}].dbo.{{StringResource}} n ON sr.text_id = n.code ORDER BY sr.state_id ASC;",
        QueryEntity.Npc => "SELECT [id] AS NPC_id, (n.[value] + ' ' + n2.[value]) AS npc_title, [x], [y], [contact_script] FROM [{{ArcadiaName}}].dbo.{{NpcResource}} nid LEFT JOIN [{{ArcadiaName}}].dbo.{{StringResource}} n ON nid.[text_id] = n.[code] LEFT JOIN [{{ArcadiaName}}].dbo.{{StringResource}} n2 ON nid.[name_text_id] = n2.[code] ORDER BY [id] ASC OFFSET 0 ROWS;",
        QueryEntity.Summons => "SELECT id.[id] AS Summon_ID, n.[value] AS Summon_Name, sn.[value] AS Card_Name, COALESCE(NULLIF(id.[face_file_name] COLLATE DATABASE_DEFAULT, '' COLLATE DATABASE_DEFAULT), ir.[icon_file_name] COLLATE DATABASE_DEFAULT) AS icon_file_name FROM [{{ArcadiaName}}].dbo.{{SummonResource}} AS id LEFT JOIN [{{ArcadiaName}}].dbo.{{StringResource}} AS n ON id.[name_id] = n.[code] LEFT JOIN [{{ArcadiaName}}].dbo.{{ItemResource}} AS ir ON id.[card_id] = ir.[id] LEFT JOIN [{{ArcadiaName}}].dbo.{{StringResource}} AS sn ON ir.[name_id] = sn.[code] WHERE id.[form] = 1 AND id.[is_riding_only] = 0 ORDER BY id.[id] ASC;",
        QueryEntity.ItemEffects => "SELECT i.[id] AS EffectId, n.[value] AS EffectText FROM [{{ArcadiaName}}].dbo.ItemEffectResource i LEFT JOIN [{{ArcadiaName}}].dbo.{{StringResource}} n ON i.[tooltip_id] = n.[code] ORDER BY i.[id];",
        _ => throw new KeyNotFoundException($"Missing MSSQL query for entity '{entity}'.")
    };

    private static string GetMysqlQuery(QueryEntity entity) => entity switch
    {
        QueryEntity.Playerchecker => "SELECT c.sid AS Player_ID, c.name AS Player_Name, c.account AS Account, c.lv AS Level, IFNULL(sr.value, '') AS Job_Name, CASE WHEN c.login_time IS NOT NULL AND (c.logout_time IS NULL OR c.logout_time < c.login_time) THEN 'ONLINE' ELSE 'OFFLINE' END AS Online_Status FROM `{{TelecasterName}}`.`Character` AS c LEFT JOIN `{{ArcadiaName}}`.`JobResource` AS jr ON c.job = jr.id LEFT JOIN `{{ArcadiaName}}`.`{{StringResource}}` AS sr ON jr.text_id = sr.code ORDER BY c.sid DESC LIMIT 100;",
        QueryEntity.PlayercheckerByCharName => "SELECT c.sid AS Player_ID, c.name AS Player_Name, c.account AS Account, c.lv AS Level, IFNULL(sr.value, '') AS Job_Name, CASE WHEN c.login_time IS NOT NULL AND (c.logout_time IS NULL OR c.logout_time < c.login_time) THEN 'ONLINE' ELSE 'OFFLINE' END AS Online_Status FROM `{{TelecasterName}}`.`Character` AS c LEFT JOIN `{{ArcadiaName}}`.`JobResource` AS jr ON c.job = jr.id LEFT JOIN `{{ArcadiaName}}`.`{{StringResource}}` AS sr ON jr.text_id = sr.code WHERE c.name LIKE @SearchTerm ORDER BY c.lv DESC LIMIT 500;",
        QueryEntity.PlayercheckerByAccount => "SELECT c.sid AS Player_ID, c.name AS Player_Name, c.account AS Account, c.lv AS Level, IFNULL(sr.value, '') AS Job_Name, CASE WHEN c.login_time IS NOT NULL AND (c.logout_time IS NULL OR c.logout_time < c.login_time) THEN 'ONLINE' ELSE 'OFFLINE' END AS Online_Status FROM `{{TelecasterName}}`.`Character` AS c LEFT JOIN `{{ArcadiaName}}`.`JobResource` AS jr ON c.job = jr.id LEFT JOIN `{{ArcadiaName}}`.`{{StringResource}}` AS sr ON jr.text_id = sr.code WHERE c.account LIKE @SearchTerm ORDER BY c.slot ASC LIMIT 500;",
        QueryEntity.PlayercheckerAll => "SELECT c.sid AS Player_ID, c.name AS Player_Name, c.account AS Account, c.lv AS Level, IFNULL(sr.value, '') AS Job_Name, CASE WHEN c.login_time IS NOT NULL AND (c.logout_time IS NULL OR c.logout_time < c.login_time) THEN 'ONLINE' ELSE 'OFFLINE' END AS Online_Status FROM `{{TelecasterName}}`.`Character` AS c LEFT JOIN `{{ArcadiaName}}`.`JobResource` AS jr ON c.job = jr.id LEFT JOIN `{{ArcadiaName}}`.`{{StringResource}}` AS sr ON jr.text_id = sr.code ORDER BY c.sid DESC;",
        QueryEntity.PlayercheckerOnline => "SELECT c.sid AS Player_ID, c.name AS Player_Name, c.account AS Account, c.lv AS Level, IFNULL(sr.value, '') AS Job_Name, 'ONLINE' AS Online_Status FROM `{{TelecasterName}}`.`Character` AS c LEFT JOIN `{{ArcadiaName}}`.`JobResource` AS jr ON c.job = jr.id LEFT JOIN `{{ArcadiaName}}`.`{{StringResource}}` AS sr ON jr.text_id = sr.code WHERE c.login_time IS NOT NULL AND (c.logout_time IS NULL OR c.logout_time < c.login_time) ORDER BY c.sid DESC;",
        QueryEntity.PlayerInventory => "SELECT i.code AS Item_ID, IFNULL(sr.value, 'Unknown') AS Item_Name, i.cnt AS Count, i.level AS Level, i.enhance AS Enhance, i.wear_info, i.awaken_sid, i.random_option_sid, i.summon_code, ir.icon_file_name AS icon_file_name FROM `{{TelecasterName}}`.`Item` AS i INNER JOIN `{{ArcadiaName}}`.`ItemResource` AS ir ON i.code = ir.id INNER JOIN `{{ArcadiaName}}`.`{{StringResource}}` AS sr ON ir.name_id = sr.code WHERE i.owner_id = @OwnerId ORDER BY i.code ASC;",
        QueryEntity.PlayerWarehouse => "SELECT i.code AS Item_ID, IFNULL(sr.value, 'Unknown') AS Item_Name, i.cnt AS Count, i.level AS Level, i.enhance AS Enhance, i.wear_info, i.awaken_sid, i.random_option_sid, i.summon_code, ir.icon_file_name AS icon_file_name FROM `{{TelecasterName}}`.`Item` AS i INNER JOIN `{{ArcadiaName}}`.`ItemResource` AS ir ON i.code = ir.id INNER JOIN `{{ArcadiaName}}`.`{{StringResource}}` AS sr ON ir.name_id = sr.code WHERE i.account_id = (SELECT a.account_id FROM `{{AuthName}}`.`{{AccountsName}}` AS a WHERE a.login_name = @AccountName LIMIT 1) ORDER BY i.code ASC;",
        QueryEntity.Monsters => "SELECT m.id, n.value AS name, m.level, v.value AS location FROM `{{ArcadiaName}}`.`{{MonsterResource}}` m LEFT JOIN `{{ArcadiaName}}`.`{{StringResource}}` n ON m.name_id = n.code LEFT JOIN `{{ArcadiaName}}`.`{{StringResource}}` v ON m.location_id = v.code ORDER BY m.id ASC;",
        QueryEntity.Items => "SELECT i.id AS Item_ID, s.value AS Name_EN, i.icon_file_name AS icon_file_name FROM `{{ArcadiaName}}`.`{{ItemResource}}` i INNER JOIN `{{ArcadiaName}}`.`{{StringResource}}` s ON i.name_id = s.code ORDER BY Item_ID ASC;",
        QueryEntity.Skills => "SELECT s.id AS Skill_id, n.value AS Skillname, s.icon_file_name AS icon_file_name FROM `{{ArcadiaName}}`.`{{SkillResource}}` s LEFT JOIN `{{ArcadiaName}}`.`{{StringResource}}` n ON s.text_id = n.code ORDER BY Skill_id ASC;",
        QueryEntity.States => "SELECT sr.state_id, n.value AS buff_name, sr.icon_file_name AS icon_file_name FROM `{{ArcadiaName}}`.`{{StateResource}}` sr LEFT JOIN `{{ArcadiaName}}`.`{{StringResource}}` n ON sr.text_id = n.code ORDER BY sr.state_id ASC;",
        QueryEntity.Npc => "SELECT nrc.id AS NPC_id, CONCAT_WS(' ', n1.value, n2.value) AS npc_title, nrc.x, nrc.y, nrc.contact_script FROM `{{ArcadiaName}}`.`{{NpcResource}}` nrc LEFT JOIN `{{ArcadiaName}}`.`{{StringResource}}` n1 ON nrc.text_id = n1.code LEFT JOIN `{{ArcadiaName}}`.`{{StringResource}}` n2 ON nrc.name_text_id = n2.code ORDER BY nrc.id ASC;",
        QueryEntity.Summons => "SELECT s.id AS Summon_ID, sn.value AS Summon_Name, cn.value AS Card_Name, COALESCE(NULLIF(s.face_file_name, ''), ir.icon_file_name) AS icon_file_name FROM `{{ArcadiaName}}`.`{{SummonResource}}` s LEFT JOIN `{{ArcadiaName}}`.`{{StringResource}}` sn ON s.name_id = sn.code LEFT JOIN `{{ArcadiaName}}`.`{{ItemResource}}` ir ON s.card_id = ir.id LEFT JOIN `{{ArcadiaName}}`.`{{StringResource}}` cn ON ir.name_id = cn.code WHERE s.form = 1 AND s.is_riding_only = 0 ORDER BY s.id ASC;",
        QueryEntity.ItemEffects => "SELECT i.id AS EffectId, n.value AS EffectText FROM `{{ArcadiaName}}`.`ItemEffectResource` i LEFT JOIN `{{ArcadiaName}}`.`{{StringResource}}` n ON i.tooltip_id = n.code ORDER BY i.id;",
        _ => throw new KeyNotFoundException($"Missing MySQL query for entity '{entity}'.")
    };

    private static string GetSqliteQuery(QueryEntity entity) => entity switch
    {
        QueryEntity.Items => "SELECT item_id, name_en, icon_file_name FROM Items ORDER BY name_en;",
        QueryEntity.Monsters => "SELECT id, name, level, location FROM Monsters ORDER BY name;",
        QueryEntity.Skills => "SELECT skill_id, skillname, icon_file_name FROM Skills ORDER BY skillname;",
        QueryEntity.States => "SELECT state_id, buff_name, icon_file_name FROM States ORDER BY buff_name;",
        QueryEntity.Npc => "SELECT npc_id, npc_title, x, y, contact_script FROM Npcs ORDER BY npc_title;",
        QueryEntity.Summons => "SELECT summon_id, summon_name, card_name, icon_file_name FROM Summons ORDER BY summon_name;",
        _ => throw new KeyNotFoundException($"Missing Sqlite query for entity '{entity}'.")
    };
}
